Add html css basics homework, exercise 8
Pavel-Shemyakin/external-courses pull request #6
Opened 2020-03-30 11:02 UTC by Pavel-Shemyakin

My homwork, lecture 8

2020-04-10 17:33 UTC, dfolomkin requested changes

2020-04-10 17:33 UTC, dfolomkin commented on src/ex8_html-css-basics/task-03.css
> +	border-color: blue;
это тоже самое, что и 1 вариант (там просто короткая запись)

2020-04-10 17:33 UTC, dfolomkin commented on src/ex8_html-css-basics/task-04.css
> +	border: 5px;
выравнивание поехало

2020-04-10 17:33 UTC, dfolomkin commented on src/ex8_html-css-basics/task-04.css
> +    0 -2px 2px #000;
нужен отступ

2020-04-12 14:08 UTC, aneelia commented on src/ex8_html-css-basics/task-04.css
> +.h_white {
эт че за название такое

2020-04-12 14:08 UTC, aneelia commented on src/ex8_html-css-basics/task-04.css
> +.Description_and_Nested_lists {
название плохое, + непонятно че за стиль именования. просто list если он используется для нескольких списков

2020-04-12 14:09 UTC, aneelia commented on src/ex8_html-css-basics/task-04.css
> +    width: 9cm;
плохая практика использовать локальные единицы измерения

2020-04-12 14:09 UTC, aneelia commented on src/ex8_html-css-basics/task-04.css
> +.h_black {
redo

2020-04-12 14:10 UTC, aneelia commented on src/ex8_html-css-basics/task-04.css
> +.text_underline {
и тут и ниже и так понятно, что это для текста

2020-04-12 14:10 UTC, aneelia commented on src/ex8_html-css-basics/task-01.css
> +.green_colored_block {
.green_block достаточно

2020-05-03 15:29 UTC, merged