Add html css basics homework, exercise 9
Pavel-Shemyakin/external-courses pull request #7
Opened 2020-04-03 18:33 UTC by Pavel-Shemyakin

My homework for lecture 9.

2020-04-10 17:47 UTC, dfolomkin requested changes

2020-04-10 17:47 UTC, dfolomkin commented on src/ex9_html-css-fundamentals-part1/task-04.css
> +
пустая строка?

2020-04-10 17:47 UTC, dfolomkin commented on src/ex9_html-css-fundamentals-part1/task-04.css
> +.div_container, .div_1, .div_2, .div_3{
нужен пробел перед скобкой {

2020-04-12 14:11 UTC, aneelia commented on src/ex9_html-css-fundamentals-part1/task-04.css
> +.div_container {
названия с div в этом файле переделать все

2020-04-12 14:11 UTC, aneelia commented on src/ex9_html-css-fundamentals-part1/task-04.css
> +.before-after {
redo

2020-05-03 15:29 UTC, merged